{{- $nameSpace := include "openblocks.namespace" . -}}
{{- $name := include "openblocks.fullname" . -}}
{{- $openblocksDatabase := first .Values.mongodb.auth.databases -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openblocks.fullname" . }}-backend
  labels:
    {{- include "openblocks.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.redis.enabled }}
  REDIS_URL: "redis://{{ $name }}-redis-master.{{ $nameSpace }}.svc.cluster.local:6379"
  {{- else }}
  REDIS_URL: {{- .Values.redis.externalUrl | quote }}
  {{- end }}
  UID: {{ .Values.backend.config.userId | default "9001" | quote }}
  GID: {{ .Values.backend.config.groupId | default "9001" | quote }}
  CORS_ALLOWED_DOMAINS: {{ .Values.backend.config.corsAllowedDomains | default  "*" | quote }}

