apiVersion: v1
kind: Service
metadata:
  name: {{ include "openblocks.fullname" . }}-backend
  labels:
    {{- include "openblocks.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: openblocks-api
      protocol: TCP
      name: openblocks-api
    {{- if .Values.backend.service.nodePort }}
      {{- if or (eq .Values.backend.service.type "NodePort") (eq .Values.backend.service.type "LoadBalancer") }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "openblocks.selectorLabels" . | nindent 4 }}
